{-
   Blockchain.com Exchange REST API
   ## Introduction Welcome to Blockchain.com's Exchange API and developer documentation. These documents detail and give examples of various functionality offered by the API such as receiving real time market data, requesting balance information and performing trades. ## To Get Started Create or log into your existing Blockchain.com Exchange account Select API from the drop down menu Fill out form and click “Create New API Key Now” Once generated you can view your keys under API Settings 

   The version of the OpenAPI document: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Balance exposing (Balance, decoder, encode, encodeWithTag, toString)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias Balance =
    { currency : String
    , balance : Float
    , available : Float
    , balanceLocal : Float
    , availableLocal : Float
    , rate : Float
    }


decoder : Decoder Balance
decoder =
    Decode.succeed Balance
        |> required "currency" Decode.string
        |> required "balance" Decode.float
        |> required "available" Decode.float
        |> required "balance_local" Decode.float
        |> required "available_local" Decode.float
        |> required "rate" Decode.float



encode : Balance -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> Balance -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : Balance -> List (String, Encode.Value)
encodePairs model =
    [ ( "currency", Encode.string model.currency )
    , ( "balance", Encode.float model.balance )
    , ( "available", Encode.float model.available )
    , ( "balance_local", Encode.float model.balanceLocal )
    , ( "available_local", Encode.float model.availableLocal )
    , ( "rate", Encode.float model.rate )
    ]



toString : Balance -> String
toString =
    Encode.encode 0 << encode




