/* 
 * Blockchain.com Exchange REST API
 *
 * ## Introduction Welcome to Blockchain.com's Exchange API and developer documentation. \\ These documents detail and give examples of various functionality offered by the API such as receiving real time market data, requesting balance information and performing trades. ## To Get Started Create or log into your existing Blockchain.com Exchange account \\ Select API from the drop down menu \\ Fill out form and click “Create New API Key Now” \\ Once generated you can view your keys under API Settings. \\ Please be aware that the API key can only be used once it was verified via email.  The API key must be set via the \\ `X-API-Token`\\ header.  The base URL to be used for all calls is \\ `https://api.blockchain.com/v3/exchange`  Autogenerated clients for this API can be found [here](https://github.com/blockchain/lib-exchange-client). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.com.blockchain.exchange.rest.api;
using Org.OpenAPITools.com.blockchain.exchange.rest.model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PriceEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriceEventTests
    {
        // TODO uncomment below to declare an instance variable for PriceEvent
        //private PriceEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PriceEvent
            //instance = new PriceEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PriceEvent
        /// </summary>
        [Test]
        public void PriceEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PriceEvent
            //Assert.IsInstanceOf(typeof(PriceEvent), instance);
        }


        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Price24h'
        /// </summary>
        [Test]
        public void Price24hTest()
        {
            // TODO unit test for the property 'Price24h'
        }
        /// <summary>
        /// Test the property 'Volume24h'
        /// </summary>
        [Test]
        public void Volume24hTest()
        {
            // TODO unit test for the property 'Volume24h'
        }
        /// <summary>
        /// Test the property 'LastTradePrice'
        /// </summary>
        [Test]
        public void LastTradePriceTest()
        {
            // TODO unit test for the property 'LastTradePrice'
        }

    }

}
