/* 
 * Blockchain.com Exchange REST API
 *
 * ## Introduction Welcome to Blockchain.com's Exchange API and developer documentation. These documents detail and give examples of various functionality offered by the API such as receiving real time market data, requesting balance information and performing trades. ## To Get Started Create or log into your existing Blockchain.com Exchange account Select API from the drop down menu Fill out form and click “Create New API Key Now” Once generated you can view your keys under API Settings 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.com.blockchain.exchange.rest.model
{
    /// <summary>
    /// CancelOrderRequest
    /// </summary>
    [DataContract]
    public partial class CancelOrderRequest :  IEquatable<CancelOrderRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines Action
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            /// <summary>
            /// Enum CancelOrderRequest for value: CancelOrderRequest
            /// </summary>
            [EnumMember(Value = "CancelOrderRequest")]
            CancelOrderRequest = 1

        }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="action", EmitDefaultValue=true)]
        public ActionEnum Action { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CancelOrderRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CancelOrderRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CancelOrderRequest" /> class.
        /// </summary>
        /// <param name="action">action (required).</param>
        /// <param name="orderID">The unique order id assigned by the exchange (required).</param>
        public CancelOrderRequest(ActionEnum action = default(ActionEnum), long orderID = default(long))
        {
            // to ensure "action" is required (not null)
            if (action == null)
            {
                throw new InvalidDataException("action is a required property for CancelOrderRequest and cannot be null");
            }
            else
            {
                this.Action = action;
            }
            
            // to ensure "orderID" is required (not null)
            if (orderID == null)
            {
                throw new InvalidDataException("orderID is a required property for CancelOrderRequest and cannot be null");
            }
            else
            {
                this.OrderID = orderID;
            }
            
        }
        

        /// <summary>
        /// The unique order id assigned by the exchange
        /// </summary>
        /// <value>The unique order id assigned by the exchange</value>
        [DataMember(Name="orderID", EmitDefaultValue=true)]
        public long OrderID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancelOrderRequest {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  OrderID: ").Append(OrderID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CancelOrderRequest);
        }

        /// <summary>
        /// Returns true if CancelOrderRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CancelOrderRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CancelOrderRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) && 
                (
                    this.OrderID == input.OrderID ||
                    (this.OrderID != null &&
                    this.OrderID.Equals(input.OrderID))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.OrderID != null)
                    hashCode = hashCode * 59 + this.OrderID.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
