/**
 * Blockchain.com Exchange REST API
 * ## Introduction Welcome to Blockchain.com's Exchange API and developer documentation. These documents detail and give examples of various functionality offered by the API such as receiving real time market data, requesting balance information and performing trades. ## To Get Started Create or log into your existing Blockchain.com Exchange account Select API from the drop down menu Fill out form and click “Create New API Key Now” Once generated you can view your keys under API Settings 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Fees model module.
 * @module com.blockchain.exchange.rest/com.blockchain.exchange.rest.model/Fees
 * @version 1.0.0
 */
class Fees {
    /**
     * Constructs a new <code>Fees</code>.
     * @alias module:com.blockchain.exchange.rest/com.blockchain.exchange.rest.model/Fees
     * @param makerRate {Number} 
     * @param takerRate {Number} 
     * @param volumeInUSD {Number} 
     */
    constructor(makerRate, takerRate, volumeInUSD) { 
        
        Fees.initialize(this, makerRate, takerRate, volumeInUSD);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, makerRate, takerRate, volumeInUSD) { 
        obj['makerRate'] = makerRate;
        obj['takerRate'] = takerRate;
        obj['volumeInUSD'] = volumeInUSD;
    }

    /**
     * Constructs a <code>Fees</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.blockchain.exchange.rest/com.blockchain.exchange.rest.model/Fees} obj Optional instance to populate.
     * @return {module:com.blockchain.exchange.rest/com.blockchain.exchange.rest.model/Fees} The populated <code>Fees</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Fees();

            if (data.hasOwnProperty('makerRate')) {
                obj['makerRate'] = ApiClient.convertToType(data['makerRate'], 'Number');
            }
            if (data.hasOwnProperty('takerRate')) {
                obj['takerRate'] = ApiClient.convertToType(data['takerRate'], 'Number');
            }
            if (data.hasOwnProperty('volumeInUSD')) {
                obj['volumeInUSD'] = ApiClient.convertToType(data['volumeInUSD'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} makerRate
 */
Fees.prototype['makerRate'] = undefined;

/**
 * @member {Number} takerRate
 */
Fees.prototype['takerRate'] = undefined;

/**
 * @member {Number} volumeInUSD
 */
Fees.prototype['volumeInUSD'] = undefined;






export default Fees;

