/**
 * Blockchain.com Exchange REST API
 * ## Introduction Welcome to Blockchain.com's Exchange API and developer documentation. These documents detail and give examples of various functionality offered by the API such as receiving real time market data, requesting balance information and performing trades. ## To Get Started Create or log into your existing Blockchain.com Exchange account Select API from the drop down menu Fill out form and click “Create New API Key Now” Once generated you can view your keys under API Settings 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TimeInForce.
* @enum {}
* @readonly
*/
export default class TimeInForce {
    
        /**
         * value: "GTC"
         * @const
         */
        "GTC" = "GTC";

    
        /**
         * value: "IOC"
         * @const
         */
        "IOC" = "IOC";

    
        /**
         * value: "FOK"
         * @const
         */
        "FOK" = "FOK";

    
        /**
         * value: "GTD"
         * @const
         */
        "GTD" = "GTD";

    

    /**
    * Returns a <code>TimeInForce</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:com.blockchain.exchange.rest/com.blockchain.exchange.rest.model/TimeInForce} The enum <code>TimeInForce</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

