/*
 * Blockchain.com Exchange REST API
 *
 * ## Introduction Welcome to Blockchain.com's Exchange API and developer documentation. These documents detail and give examples of various functionality offered by the API such as receiving real time market data, requesting balance information and performing trades. ## To Get Started Create or log into your existing Blockchain.com Exchange account Select API from the drop down menu Fill out form and click “Create New API Key Now” Once generated you can view your keys under API Settings 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BaseOrder struct for BaseOrder
type BaseOrder struct {
	// Reference field provided by client and cannot exceed 20 characters
	ClOrdId string `json:"clOrdId"`
	OrdType OrdType `json:"ordType"`
	// Blockchain symbol identifier
	Symbol string `json:"symbol"`
	Side Side `json:"side"`
	// The order size in the terms of the base currency
	OrderQty float64 `json:"orderQty"`
	TimeInForce TimeInForce `json:"timeInForce,omitempty"`
	// The limit price for the order
	Price float64 `json:"price,omitempty"`
	// expiry date in the format YYYYMMDD
	ExpireDate int32 `json:"expireDate,omitempty"`
	// The minimum quantity required for an IOC fill
	MinQty float64 `json:"minQty,omitempty"`
	// The limit price for the order
	StopPx float64 `json:"stopPx,omitempty"`
}
