/**
 * Blockchain.com Exchange REST API
 * ## Introduction Welcome to Blockchain.com's Exchange API and developer documentation. \\ These documents detail and give examples of various functionality offered by the API such as receiving real time market data, requesting balance information and performing trades. ## To Get Started Create or log into your existing Blockchain.com Exchange account \\ Select API from the drop down menu \\ Fill out form and click “Create New API Key Now” \\ Once generated you can view your keys under API Settings. \\ Please be aware that the API key can only be used once it was verified via email.  The API key must be set via the \\ `X-API-Token`\\ header.  The base URL to be used for all calls is \\ `https://api.blockchain.com/v3/exchange`  Autogenerated clients for this API can be found [here](https://github.com/blockchain/lib-exchange-client). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.blockchain.exchange.rest.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreateWithdrawalRequest {
  
  @SerializedName("amount")
  private Double amount = null;
  @SerializedName("currency")
  private String currency = null;
  @SerializedName("beneficiary")
  private String beneficiary = null;
  @SerializedName("sendMax")
  private Boolean sendMax = null;

  /**
   * The amount to withdraw in the currency specified
   **/
  @ApiModelProperty(value = "The amount to withdraw in the currency specified")
  public Double getAmount() {
    return amount;
  }
  public void setAmount(Double amount) {
    this.amount = amount;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getBeneficiary() {
    return beneficiary;
  }
  public void setBeneficiary(String beneficiary) {
    this.beneficiary = beneficiary;
  }

  /**
   * If set, sends the full available amount, minus fees. Amount may not be specified in that case. 
   **/
  @ApiModelProperty(value = "If set, sends the full available amount, minus fees. Amount may not be specified in that case. ")
  public Boolean getSendMax() {
    return sendMax;
  }
  public void setSendMax(Boolean sendMax) {
    this.sendMax = sendMax;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWithdrawalRequest createWithdrawalRequest = (CreateWithdrawalRequest) o;
    return (this.amount == null ? createWithdrawalRequest.amount == null : this.amount.equals(createWithdrawalRequest.amount)) &&
        (this.currency == null ? createWithdrawalRequest.currency == null : this.currency.equals(createWithdrawalRequest.currency)) &&
        (this.beneficiary == null ? createWithdrawalRequest.beneficiary == null : this.beneficiary.equals(createWithdrawalRequest.beneficiary)) &&
        (this.sendMax == null ? createWithdrawalRequest.sendMax == null : this.sendMax.equals(createWithdrawalRequest.sendMax));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    result = 31 * result + (this.currency == null ? 0: this.currency.hashCode());
    result = 31 * result + (this.beneficiary == null ? 0: this.beneficiary.hashCode());
    result = 31 * result + (this.sendMax == null ? 0: this.sendMax.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWithdrawalRequest {\n");
    
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  currency: ").append(currency).append("\n");
    sb.append("  beneficiary: ").append(beneficiary).append("\n");
    sb.append("  sendMax: ").append(sendMax).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
