/**
 * Blockchain.com Exchange REST API
 * ## Introduction Welcome to Blockchain.com's Exchange API and developer documentation. \\ These documents detail and give examples of various functionality offered by the API such as receiving real time market data, requesting balance information and performing trades. ## To Get Started Create or log into your existing Blockchain.com Exchange account \\ Select API from the drop down menu \\ Fill out form and click “Create New API Key Now” \\ Once generated you can view your keys under API Settings. \\ Please be aware that the API key can only be used once it was verified via email.  The API key must be set via the \\ `X-API-Token`\\ header.  The base URL to be used for all calls is \\ `https://api.blockchain.com/v3/exchange`  Autogenerated clients for this API can be found [here](https://github.com/blockchain/lib-exchange-client). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.blockchain.exchange.rest.model;

import com.blockchain.exchange.rest.model.OrderBookEntry;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderBook {
  
  @SerializedName("symbol")
  private String symbol = null;
  @SerializedName("bids")
  private List<OrderBookEntry> bids = null;
  @SerializedName("asks")
  private List<OrderBookEntry> asks = null;

  /**
   * Blockchain symbol identifier
   **/
  @ApiModelProperty(value = "Blockchain symbol identifier")
  public String getSymbol() {
    return symbol;
  }
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<OrderBookEntry> getBids() {
    return bids;
  }
  public void setBids(List<OrderBookEntry> bids) {
    this.bids = bids;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<OrderBookEntry> getAsks() {
    return asks;
  }
  public void setAsks(List<OrderBookEntry> asks) {
    this.asks = asks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderBook orderBook = (OrderBook) o;
    return (this.symbol == null ? orderBook.symbol == null : this.symbol.equals(orderBook.symbol)) &&
        (this.bids == null ? orderBook.bids == null : this.bids.equals(orderBook.bids)) &&
        (this.asks == null ? orderBook.asks == null : this.asks.equals(orderBook.asks));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.symbol == null ? 0: this.symbol.hashCode());
    result = 31 * result + (this.bids == null ? 0: this.bids.hashCode());
    result = 31 * result + (this.asks == null ? 0: this.asks.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderBook {\n");
    
    sb.append("  symbol: ").append(symbol).append("\n");
    sb.append("  bids: ").append(bids).append("\n");
    sb.append("  asks: ").append(asks).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
